### PR TITLE
Morty page rough draft

### PR DESCRIPTION
**Pull request by apreece13**
I created a rough draft for the Morty Page. None of the buttons work.

There should be a styled jumbo tron with text. there should also be a place to log in. All styled with CSS.

### CODE REVIEW

**Review by DerekStapleton21 — COMMENTED** [review]
Looks good, bro!

**Comment by AWoodbury01** [comment]
Looks good to me!

**Comment by apreece13** [comment]
Adding updated morty page code

**Comment by apreece13** [comment]
.

**Pull request closed without merging**
